apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: default
spec:
  secretName: my-tls-secret
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  commonName: "35.244.201.19"
  ipAddresses:
    - "35.244.201.19"
