apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: inventory-app
  labels:
    type: local
    app: mysql
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/mysql/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: inventory-app
  labels:
    app: mysql
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
