apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-store
  labels:
    name: mysql-data-store
    app: mysql-gke-deployment
spec:
  resources:
    requests:
      storage: 3Gi
    limits:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
