apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-allow-backend-to-db
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mysql-deploy
      ports:
      - protocol: TCP
        port: 3306

