server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://172.21.32.1:3306/container
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true